12 enviroment
shmorish/21sh pull request #15
Opened 2024-07-22 14:12 UTC by shmorish

やったこと
- envの受けとり
- envのparse
- env 構造体の定義
- env_print, env_export_printで出力可能にした。

#12

2024-07-22 14:12 UTC, shmorish commented
test 落ちてた。治すからreviewそのあとで。。。

2024-07-23 12:50 UTC, tkuramot requested changes
mallocのところだけ気になりました。それ以外はめっちゃよさそうです。

2024-07-23 12:50 UTC, tkuramot commented on includes/env.h
> +	bool	hidden;
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
shell変数と環境変数の区別か

2024-07-23 12:50 UTC, tkuramot commented on includes/env.h
> +	t_env	*prev;
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
libftに双方向リストあったけど、中間のノード削除したりノード検索したりする関数がないから新しく作った感じですか？

2024-07-23 12:50 UTC, tkuramot commented on srcs/env/env_init.c
> +	head = add_env_value(head, new_env);
![must-badge](https://img.shields.io/badge/review-must-red.svg)
`create_env`でも特に処理してないから`malloc`の失敗考慮したほうがいいかもしれないです
`error.h`のなかに`or_exit`っていうの作ってるので、それ使うと行数使わずにいけるかもです

2024-07-23 12:50 UTC, tkuramot commented on srcs/env/delete_env_value.c
> +		if (!ft_memcmp(current->name, key, ft_strlen(key) + 1))
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
シンプルで安全に完全一致確かめられるのいいですね
こうすればいいのか

2024-07-24 03:26 UTC, shmorish commented on includes/env.h
> +	t_env	*prev;
あったのね。。。
これは完全に新しく作りました！

2024-07-24 03:27 UTC, shmorish commented on srcs/env/env_init.c
> +	head = add_env_value(head, new_env);
了解です👍
strdup, itoaのmalloc処理はlibftの中で入れますか？

2024-07-25 04:23 UTC, tkuramot commented on srcs/env/env_init.c
> +	head = add_env_value(head, new_env);
libftの関数は汎用性高くしたいから外側でやっちゃうのが良さそうです

2024-07-25 04:24 UTC, tkuramot commented on includes/env.h
> +	t_env	*prev;
> 中間のノード削除したりノード検索したりする関数

ここら辺作って置き換えますか？

2024-07-25 07:00 UTC, shmorish commented on srcs/env/env_init.c
> +	head = add_env_value(head, new_env);
了解です。

2024-07-25 07:01 UTC, shmorish commented on includes/env.h
> +	t_env	*prev;
あったらとても助かるけど、中間ノードの削除だけでよさそう。
ノード検索は関数ポインタかなんかを受け取ってできるかな？

2024-07-25 11:34 UTC, tkuramot commented on includes/env.h
> +	t_env	*prev;
検索したノードをどうやって返すのかが面倒になりそうな気もするから一応両方作っちゃいます

2024-08-13 05:03 UTC, tkuramot reviewed
一つコメントしました

2024-08-13 05:03 UTC, tkuramot commented on srcs/env/delete_env_value.c
> +				store_env_head(NULL);
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
pop_envしなくても良い？

2024-08-13 05:08 UTC, shmorish commented on srcs/env/delete_env_value.c
> +				store_env_head(NULL);
最後の一つに関してはnode のつなげ直しが必要ないのでpopの処理を行っていませんが
freeはどのみちいりますね。
修正します。

2024-08-13 05:16 UTC, tkuramot approved these changes
👍

2024-08-13 05:37 UTC, merged