ビルドテストのworkflowを追加する
shmorish/21sh pull request #4
Opened 2024-04-29 15:00 UTC by tkuramot

2024-05-01 13:31 UTC, shmorish commented on Makefile
> +CFLAGS		+= -I readline/include -I libft/include
```
INC := $(shell find . -name "*.h" -exec dirname {} \; | sort -u | sed 's/^/-I /' | tr '\n' ' ')
```
これでカバーできているから不要だと思う。

2024-05-01 13:33 UTC, shmorish requested changes
Makefileの箇所の確認をお願いします。

2024-05-01 15:13 UTC, tkuramot commented on Makefile
> +CFLAGS		+= -I readline/include -I libft/include
done

2024-05-02 03:49 UTC, shmorish approved these changes
ありがとうございます。

2024-05-02 11:23 UTC, merged