lexer
shmorish/21sh pull request #9
Opened 2024-07-12 09:08 UTC by tkuramot

2024-07-13 15:50 UTC, tkuramot commented on Makefile
> -	make -C ./readline clean
ライブラリなのでインストール以降の変更ないだろうしcleanしないようにしました

2024-07-13 16:31 UTC, tkuramot commented
$(command) \`command`

2024-07-14 17:32 UTC, tkuramot commented on srcs/error/error.c
> +	set_exit_status(EXIT_SYNTAX_ERROR);
bash5.2だとsyntax errorでexit statusが2になるのでとりあえずそうしてます

2024-07-15 08:30 UTC, shmorish requested changes

2024-07-15 08:30 UTC, shmorish commented on srcs/lexer/tokenize.c
<img width="244" alt="スクリーンショット 2024-07-15 17 18 06" src="https://github.com/user-attachments/assets/922837ad-6367-442f-9b72-807c445228a5">


こういう場合に
`$$`と`$(`で分けるのがよさそう。

2024-07-15 08:30 UTC, shmorish commented on srcs/lexer/tokenize.c
あと、完全に僕の記憶違いならいいのですが、

<img width="241" alt="スクリーンショット 2024-07-15 17 26 14" src="https://github.com/user-attachments/assets/cd77d622-b13e-4f1a-95e0-6c84c970ab85">


これって対応しないのでしたっけ？（結構簡単だからしてもよさそう）

2024-07-15 08:30 UTC, shmorish commented on srcs/main.c
> -			exit_command_line(exit_status);
あれ、exit_command_lineはなんで消したのです？

2024-07-15 11:57 UTC, tkuramot commented on srcs/lexer/tokenize.c
`echo $$$()`は対応しました

パラメータ展開はdiscordで

2024-07-15 11:58 UTC, tkuramot commented on srcs/main.c
> -			exit_command_line(exit_status);
間違えて消しちゃってますね。戻します。見つけてくれて感謝。

2024-07-20 16:08 UTC, shmorish approved these changes
さいこう。ほんまありがとう。

2024-07-20 16:23 UTC, merged